/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users.route'
import { Route as IndexRouteImport } from './routes/index.route'
import { Route as UsersIdRouteImport } from './routes/users.$id.route'

// Create/Update Routes

const UsersRouteRoute = UsersRouteImport.update({
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIdRouteRoute = UsersIdRouteImport.update({
  path: '/$id',
  getParentRoute: () => UsersRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRoute
    }
    '/users/$id': {
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof UsersRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRouteRoute,
  UsersRouteRoute.addChildren([UsersIdRouteRoute]),
])

/* prettier-ignore-end */
